    create table coffee(
                           id int primary key generated by default as identity,
                           name varchar(50) not null,
    );

create table ingredient(
                           id int primary key generated by default as identity ,
                           name varchar(50) not null,
                           quantity int,
                           coffee_id int references coffee(id)
);

create table resource(
                         id int primary key generated by default as identity ,
                         name varchar(50) not null,
                         quantity int check ( -1 < quantity )
);

create table rates(
                      id int primary key generated by default as identity,
                      order_number int check ( order_number > -1),
                      coffee_id int references coffee(id)
);